---
- name: update network interfaces
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
    backup: yes
  when: network_interfaces_reconfigure
  notify: restart network
